spring:
  application:
    name: DynamicQrGenerator
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 7878